 trigger:
 - workspace_publish

 pool:
   vmImage: 'windows-latest'

 steps:
   # to do: add testing
   # to do: add notebook auto initialization
   - task: Synapse workspace deployment@2
     inputs:
       operation: 'deploy'
       TemplateFile: '$(System.DefaultWorkingDirectory)/_myARMtemplates_dev/synapse-met-cicd-dev/TemplateForWorkspace.json'
       ParametersFile: '$(System.DefaultWorkingDirectory)/_myARMtemplates_dev/synapse-met-cicd-dev/TemplateParametersForWorkspace.json'
       azureSubscription: 'MCAPS-Hybrid-REQ-44911-2022-josealonso (cb72b49c-6479-4ec7-891f-f18be9ee10f2)'
       ResourceGroupName: 'aaaaaatest'
       TargetWorkspaceName: 'synapse-met-cicd-uat'
       DeleteArtifactsNotInTemplate: false
       DeployManagedPrivateEndpoints: false
       FailOnMissingOverrides: false
       Environment: 'prod'
       npmpackage: 'prod'
